### ISSUE TITLE
Revisión Arquitectura

### ISSUE THREAD

**Issue by cidinene** [Arquisoft/viade_es5b#19]
**1.Introduction   and Goal** | 
1.1   Requirements Overview | realizado con   comentarios | 

- _La   interoperabilidad es un technical requirement_

1.2 Quality   Goals | realizado |  
1.3   Stakeholders | realizado |  
**2.Architecture   Constraints** | realizado con comentarios |
 

- _Hay muchas  restricciones que  no son restricciones como tal, sino como ya   soluciones para resolver un problema, irían más bien en Design Decision ,   Solution Strategy o Risks_

**3.System Scope   and Context** 
3.1 Business   Context | realizado |  
3.2 Technical   Context | realizado con   comentarios | 

- _Falta Servicio   de Mapas_

**4.Solution   Strategy** | no realizado |  
**5.Building   Block View** | 
5.1 WhiteBox   Overall System | realizado |  
5.2 Level 2 | realizado |  
**6.RuntimeViewer** 
6.1 Runtime   Scenario 1 | realizado con   comentarios | 

- _Falta los   diagramas de secuencia_

6.2 Runtime   Scenario 2 | no realizado |  
**7.Deployment   View** 
7.1   Infraestructura Level 1 | realizado |  
7.2   Infraestructura Level 2 |  realizado con comentarios |
 Este apartado   debería contener un refinamiento de la infraestructura de nivel 2, no ser   diferente
**8.Cross-cutting   Concepts** 
8.1   Conceptos | realizado |  
**9.Design   Decisions** | realizado con   comentarios | 

- _Hay decisiones   en los diagramas que no están incluidas en este apartado:rdflib, googlemaps,   arc42_

**10. Quality   Requirements**   
10.1 Quality   Tree | realizado con   comentarios |

-  _A trabajar más   en siguientes iteracciones_

10.2 Quality   Scenarios | realizado con   comentarios | 

- _A trabajar más   en siguientes iteracciones_

**11. Risk and   Technical Debts** | realizado |  
**12. Glossary** | no realizado |

**Comment by AlejandroIglesiasCalvo** [comment]
- Sobre el punto 10
Claro, conforme trabajemos en la aplicación se irán completando, añadiendo y perfilando los requisitos. Por ahora comenzamos con cosas simples y poco concretas.
Trabajaremos en ello.

**Comment by alex-florez** [comment]
Documentación actualizada.
