### ISSUE TITLE
Corregir UI EliminarRuta

### ISSUE THREAD

**Issue by alex-florez** [Arquisoft/viade_es5b#22]
A la hora de eliminar una ruta, se hace click sobre "Eliminar" pero la vista no se actualiza, y por tanto se sigue mostrando el panel con toda la información de la ruta. Cambiarlo para que al eliminar la ruta se actualice el componente y no se muestre la ruta recién eliminada.

**Comment by pedrojosefernandezfranco** [comment]
Ya esta arreglado, el problema era que el metodo de borrar era asincrono pero no tenia valor de retorno, entonces no se podia esperar por el, ahora devuelve la lista de rutas actualizada.
