### ISSUE TITLE
Revisión prototipo

### ISSUE THREAD

**Issue by cidinene** [Arquisoft/viade_es5b#31]
Como comentado en el meeting que tuve con vosotros,  vuestro prototipo tiene varios puntos fuertes : la  interfaz de mostrar ruta con la opción de añadir imágenes y comentarios funciona bien, y en una sola ventana puedes visualizarlo todo . También está muy bien lo de compartir rutas, enviando la notificación a los amigos. 
Cosas que se pueden mejorar: 
- La creación de rutas . la interfaz es muy básica . Habría que mejorarla. 
Funcionalidades nuevas :
- Importar ficheros geojson, gpx

Tenéis test (habrá que comprobar el porcentaje de cobertura cuando consigamos solucionar el error de token ) y no  las pruebas de aceptación.El código está actualizado, así que solo me queda felicitaros por vuestro trabajo.  Feliz Semana Santa

Un saludo

**Comment by alex-florez** [comment]
Ahora las rutas se pueden crear a partir de un mapa, lo cual es bastante intuitivo y sencillo. En cuanto a  importar ficheros no ha sido implementado.
