### ISSUE TITLE
Improvements after presentation

### ISSUE THREAD

**Issue by alex-florez** [Arquisoft/viade_es5b#40]
Apartados arreglados de la documentación:

- 4.) Solution Strategy - Actualizada la tabla de tecnologías y la descripción de los enfoques tomados para el desarrollo del proyecto. Actualizado el diagrama de descomposición de alto nivel, incluyendo leyenda de colores, y explicación del diagrama.  #38 
- 5.) Building Block View - Creados nuevos diagramas de bloques con cajas negras y blancas incluyendo leyenda, ordenados por nivel y con descripción de las cajas negras y sus interacciones. #35

**Comment by UO245503** [comment]
Apartados arreglados de la documentación:

- Apartado 10.2 escenarios de calidad: Se ha realizado escenarios de calidad  concretos. #37 

- 7) Deployment view: Se han añadido las leyendas a los diagramas.

**Comment by uo265060** [comment]
Apartados arreglados de la documentación:

- Traducción a español de toda la documentación.

- 6.) Runtime View: Incluir una leyenda para el escenario 1 y reflejar los participantes en los diagramas del resto de escenarios.
